name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # Added npm caching for faster builds

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set environment variables
        env:
          SALT: ${{ secrets.SALT }}
        run: |
          echo "SALT environment variable is set"
          # Never echo the actual secret value for security
          echo "SALT length: ${#SALT}"

      - name: Run Playwright tests
        env:
          SALT: ${{ secrets.SALT }}
          # Add other environment variables here if needed
          CI: true
          NODE_ENV:
        run: npx playwright test ./src/tests/LoginTest.spec.ts --reporter=html
        continue-on-error: false # Set to true if you want pipeline to continue even if tests fail

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always() # Upload report even if tests fail
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7

      # Optional: Add test summary to GitHub PR/commit
      - name: Add Test Summary
        if: always()
        run: |
          echo "## 🧪 Playwright Test Results" >> $GITHUB_STEP_SUMMARY
          echo "Tests have been executed. Check the artifacts for detailed reports." >> $GITHUB_STEP_SUMMARY
          if [ -f "playwright-report/index.html" ]; then
            echo "📊 HTML report generated successfully" >> $GITHUB_STEP_SUMMARY
          fi
